baseURL = 'https://kaustav.net/'
locale = 'en-us'
title = 'Kaustav Ghosh'
enableRobotsTXT = true

[params]
  description = 'Real-Time Video, BWE, Codecs, and more.'
  author = 'Kaustav Ghosh'
  keywords = ['WebRTC', 'RTC', 'Chromium', 'bandwidth estimation', 'congestion control', 'GCC', 'video engineering']
  images = []

  [params.social]
    github = 'https://github.com/kaustav-net'

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    guessSyntax = true

[permalinks]
  posts = '/:year/:month/:title/'

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']
  taxonomy = ['HTML']
  term = ['HTML']

[taxonomies]
  tag = 'tags'

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
